from __future__ import annotations

INSTITUTIONAL_STRATEGIES = [
    {
        "id": "htf-trend-continuation",
        "name": "HTF Trend Continuation",
        "category": "trend",
        "description": "Trades pullbacks in the direction of H1/H4/D1 gold structure after momentum confirmation.",
        "bestSessions": ["London", "New York", "London-NY Overlap"],
        "idealRegimes": ["Strong Bullish Trend", "Strong Bearish Trend", "Volatility Expansion"],
        "requiredEvidence": ["HTF alignment", "clean pullback", "candle close confirmation", "room to target"],
        "avoidWhen": ["late entry", "HTF conflict", "major news blackout", "spread expansion"],
        "minConfidence": 84,
        "sniperConfidence": 92,
        "enabled": True,
        "winRate": 68.4,
        "expectancy": "1.42R",
        "maxDrawdown": "12.6%",
    },
    {
        "id": "liquidity-sweep-ob-retest",
        "name": "Liquidity Sweep + Order Block Retest",
        "category": "smc",
        "description": "Waits for a stop-hunt sweep, reclaim, displacement, and order-block retest before entry.",
        "bestSessions": ["London", "New York"],
        "idealRegimes": ["Liquidity Raid", "Strong Trend", "Range Break"],
        "requiredEvidence": ["liquidity already swept", "order block reaction", "displacement candle", "volume confirmation"],
        "avoidWhen": ["sweep not recovered", "entry too far from OB", "choppy candles"],
        "minConfidence": 86,
        "sniperConfidence": 93,
        "enabled": True,
        "winRate": 71.2,
        "expectancy": "1.58R",
        "maxDrawdown": "10.4%",
    },
    {
        "id": "london-open-breakout",
        "name": "London Open Breakout",
        "category": "session",
        "description": "Trades the London open expansion only after Asian range liquidity is cleared and spread is normal.",
        "bestSessions": ["London"],
        "idealRegimes": ["Compression Breakout", "Volatility Expansion"],
        "requiredEvidence": ["Asian range defined", "break and retest", "London volume", "no immediate red news"],
        "avoidWhen": ["false break", "wide spread", "late after first impulse"],
        "minConfidence": 82,
        "sniperConfidence": 91,
        "enabled": True,
        "winRate": 64.2,
        "expectancy": "1.31R",
        "maxDrawdown": "11.8%",
    },
    {
        "id": "new-york-reversal-continuation",
        "name": "New York Reversal / Continuation",
        "category": "session",
        "description": "Classifies NY open as continuation or reversal depending on London extension, liquidity, and macro direction.",
        "bestSessions": ["New York", "London-NY Overlap"],
        "idealRegimes": ["Trend Continuation", "Session Reversal", "Macro Repricing"],
        "requiredEvidence": ["NY liquidity event", "DXY/yields check", "structure confirmation"],
        "avoidWhen": ["mixed macro", "first news candle", "thin liquidity"],
        "minConfidence": 83,
        "sniperConfidence": 92,
        "enabled": True,
        "winRate": 62.8,
        "expectancy": "1.27R",
        "maxDrawdown": "12.1%",
    },
    {
        "id": "asian-range-liquidity-raid",
        "name": "Asian Range Liquidity Raid",
        "category": "liquidity",
        "description": "Uses the quiet Asian range as a liquidity map, then trades the sweep/reclaim around London transition.",
        "bestSessions": ["Asia", "Pre-London", "London"],
        "idealRegimes": ["Range", "Liquidity Raid"],
        "requiredEvidence": ["range high/low mapped", "sweep", "reclaim", "no spread spike"],
        "avoidWhen": ["range too wide", "macro news pending", "no reclaim"],
        "minConfidence": 80,
        "sniperConfidence": 90,
        "enabled": True,
        "winRate": 60.9,
        "expectancy": "1.14R",
        "maxDrawdown": "9.9%",
    },
    {
        "id": "vwap-mean-reversion",
        "name": "VWAP Mean Reversion",
        "category": "mean-reversion",
        "description": "Fades stretched gold moves back toward VWAP/value when trend strength is weak and liquidity is exhausted.",
        "bestSessions": ["London Mid", "New York Mid"],
        "idealRegimes": ["Range", "Weak Trend", "Exhaustion"],
        "requiredEvidence": ["distance from VWAP", "exhaustion candle", "support/resistance reaction"],
        "avoidWhen": ["strong trend", "news impulse", "no rejection candle"],
        "minConfidence": 78,
        "sniperConfidence": 88,
        "enabled": True,
        "winRate": 57.9,
        "expectancy": "0.94R",
        "maxDrawdown": "9.4%",
    },
    {
        "id": "volatility-compression-breakout",
        "name": "Volatility Compression Breakout",
        "category": "volatility",
        "description": "Waits for ATR/Bollinger compression, then trades expansion only after direction confirmation.",
        "bestSessions": ["London", "New York"],
        "idealRegimes": ["Compression", "Expansion"],
        "requiredEvidence": ["ATR compression", "range break", "volume expansion", "retest"],
        "avoidWhen": ["fake expansion", "no retest", "spread widening"],
        "minConfidence": 82,
        "sniperConfidence": 91,
        "enabled": True,
        "winRate": 63.4,
        "expectancy": "1.29R",
        "maxDrawdown": "11.0%",
    },
    {
        "id": "post-news-repricing",
        "name": "Post-News Repricing Strategy",
        "category": "news",
        "description": "Does not trade the first spike; waits for news spread normalization and the real repricing direction.",
        "bestSessions": ["New York", "London-NY Overlap"],
        "idealRegimes": ["Macro Repricing", "High Volatility"],
        "requiredEvidence": ["news released", "spread normalized", "directional reclaim", "macro alignment"],
        "avoidWhen": ["pre-news", "first whipsaw candle", "abnormal slippage"],
        "minConfidence": 84,
        "sniperConfidence": 92,
        "enabled": True,
        "winRate": 59.6,
        "expectancy": "1.36R",
        "maxDrawdown": "13.2%",
    },
    {
        "id": "fvg-fill-continuation",
        "name": "FVG Fill Continuation",
        "category": "smc",
        "description": "Trades continuation when price returns into a fair value gap aligned with HTF trend and order flow.",
        "bestSessions": ["London", "New York"],
        "idealRegimes": ["Strong Trend", "Displacement"],
        "requiredEvidence": ["FVG formed", "partial fill", "trend alignment", "rejection candle"],
        "avoidWhen": ["full invalidation", "opposite CHOCH", "target too close"],
        "minConfidence": 83,
        "sniperConfidence": 91,
        "enabled": True,
        "winRate": 65.7,
        "expectancy": "1.34R",
        "maxDrawdown": "10.8%",
    },
    {
        "id": "htf-sr-rejection",
        "name": "HTF Support/Resistance Rejection",
        "category": "structure",
        "description": "Trades clean rejection from H1/H4/D1 zones only when wick reaction, volume, and confirmation align.",
        "bestSessions": ["London", "New York", "Overlap"],
        "idealRegimes": ["Range", "Reversal", "Trend Pullback"],
        "requiredEvidence": ["HTF level", "wick rejection", "confirmation close", "room to target"],
        "avoidWhen": ["level already consumed", "no rejection", "late entry"],
        "minConfidence": 82,
        "sniperConfidence": 91,
        "enabled": True,
        "winRate": 62.3,
        "expectancy": "1.21R",
        "maxDrawdown": "10.6%",
    },
    {
        "id": "no-trade-standby",
        "name": "No-Trade / Standby Strategy",
        "category": "protection",
        "description": "The most important strategy: blocks trades when conditions are dirty, late, risky, or statistically weak.",
        "bestSessions": ["All"],
        "idealRegimes": ["Chop", "News Blackout", "Spread Expansion", "Low Edge"],
        "requiredEvidence": ["one or more hard blocks"],
        "avoidWhen": [],
        "minConfidence": 0,
        "sniperConfidence": 0,
        "enabled": True,
        "winRate": 100.0,
        "expectancy": "Capital Protection",
        "maxDrawdown": "0.0%",
    },
]
