import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { Card, Checklist, ConfidenceRing, DataTable, MetricCard, PageHeader, SectionTitle, SideBadge, Tag } from '../components/ui';
import { MiniCandleBlock } from '../components/Charts';
import { api } from '../lib/api';
import crownUrl from '../assets/godmode-crown.svg';
const money=(v:any,c='')=>`${Number(v||0)>=0?'+':''}${c?c+' ':''}${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
export default function Journal(){
  const [entries,setEntries]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[query,setQuery]=useState(''),[outcome,setOutcome]=useState('ALL'),[strategy,setStrategy]=useState('ALL'),[symbol,setSymbol]=useState('ALL');
  const [dateFrom,setDateFrom]=useState('');
  const load=async()=>{const d=await api.journal(dateFrom||undefined); const arr=Array.isArray(d)?d:[]; setEntries(arr); setSelected((x:any)=>x||arr[0]||null)};
  useEffect(()=>{load(); const id=setInterval(load,10000); return()=>clearInterval(id)},[dateFrom]);
  const filtered=useMemo(()=>entries.filter(e=>(outcome==='ALL'||e.outcome===outcome)&&(strategy==='ALL'||String(e.strategy||'').includes(strategy))&&(symbol==='ALL'||String(e.symbol||'').includes(symbol))&&(query===''||JSON.stringify(e).toLowerCase().includes(query.toLowerCase()))),[entries,outcome,strategy,symbol,query]);
  const wins=entries.filter(e=>e.outcome==='WIN').length,total=entries.length,winRate=total?Math.round((wins/total)*1000)/10:0,net=entries.reduce((a,e)=>a+Number(e.pnl||e.pnlUsd||0),0);
  const current=selected||filtered[0]||{};
  return <div className="journal-page">
    <PageHeader title="Journal" subtitle="Review, track, and optimize every trade. Build consistency through reflection." right={<button className="gold-button"><Plus size={14}/> New Journal Entry</button>}/>
    <Card className="journal-filter-card"><div className="filter-row journal-filter"><label><span>Date Range</span><input className="input" type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label><span>Outcome</span><select className="input" value={outcome} onChange={e=>setOutcome(e.target.value)}><option>ALL</option><option>WIN</option><option>LOSS</option></select></label><label><span>Strategy</span><select className="input" value={strategy} onChange={e=>setStrategy(e.target.value)}><option>ALL</option><option>London</option><option>Trend</option><option>Liquidity</option></select></label><label><span>Symbols</span><select className="input" value={symbol} onChange={e=>setSymbol(e.target.value)}><option>ALL</option><option>XAUUSD</option></select></label><label><span>Market Regime</span><select className="input"><option>All Market Regimes</option></select></label><button className="outline-button"><SlidersHorizontal size={14}/> More Filters</button><label className="search-compact"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search journal entries..."/></label></div></Card>
    <div className="journal-summary"><MetricCard label="Total Trades" value={total}/><MetricCard label="Win Rate" value={`${winRate}%`}/><MetricCard label="Profit Factor" value="—"/><MetricCard label="Total PnL" value={money(net,current.currency||'')}/><MetricCard label="Avg R Multiple" value="—"/><MetricCard label="Best Trade" value={money(Math.max(0,...entries.map(e=>Number(e.pnl||e.pnlUsd||0))),current.currency||'')}/><MetricCard label="Worst Trade" value={money(Math.min(0,...entries.map(e=>Number(e.pnl||e.pnlUsd||0))),current.currency||'')}/></div>
    <div className="journal-layout">
      <Card className="journal-list-card"><div className="button-wrap space-between"><span className="muted tiny">Sort: Newest first</span><span className="muted tiny">{filtered.length} entries</span></div><div className="journal-list">{filtered.length?filtered.map((e,i)=><div className={`journal-item ${current===e?'active':''}`} onClick={()=>setSelected(e)} key={i}><MiniCandleBlock data={e.candles} side={e.direction||e.side}/><div><strong className="journal-symbol"><span className="journal-symbol-text">XAU</span> {e.symbol||'XAUUSD'}</strong><div className="tiny muted">{e.strategy||'GodMode Strategy'}</div><div className="button-wrap"><SideBadge side={e.direction||e.side||'BUY'}/><span className={Number(e.pnl||e.pnlUsd)>=0?'positive':'negative'}>{money(e.pnl||e.pnlUsd,e.currency||'')}</span></div></div><div className="journal-time"><span>{e.time||e.closeTime||'—'}</span><Tag color={e.outcome==='WIN'?'green':e.outcome==='LOSS'?'red':'gold'}>{e.outcome||'—'}</Tag></div></div>):<p className="muted">No bot-only journal entries yet. Journal populates from GodMode magic/comment trade history.</p>}</div></Card>
      <div className="journal-detail"><Card><div className="button-wrap space-between"><div><h2 className="journal-detail-title"><span className="journal-symbol-text" style={{width:28,height:28,fontSize:10}}>XAU</span> {current.symbol||'XAUUSD'} <SideBadge side={current.direction||current.side||'—'}/></h2><p className="muted">{current.date||current.closeTime||'Select a trade from the list'} · {current.ticket?`Ticket #${current.ticket}`:'No trade selected'}</p></div><div className="journal-outcome"><Tag color={current.outcome==='WIN'?'green':current.outcome==='LOSS'?'red':'gold'}>{current.outcome||'—'}</Tag><h2 className={Number(current.pnl||current.pnlUsd)>=0?'positive':'negative'}>{money(current.pnl||current.pnlUsd,current.currency||'')}</h2></div></div><div className="grid grid-2" style={{marginTop:16}}><Card soft><SectionTitle title="Trade Chart"/><MiniCandleBlock data={current.candles} side={current.direction||current.side} height={150}/></Card><Card soft><SectionTitle title="Trade Recap"/><DataTable columns={['Metric','Value']} rows={[{Metric:'Pair',Value:current.symbol||'—'},{Metric:'Direction',Value:current.direction||current.side||'—'},{Metric:'Entry Price',Value:current.entryPrice||'—'},{Metric:'Exit Price',Value:current.exitPrice||'—'},{Metric:'Stop Loss',Value:current.sl||'—'},{Metric:'Take Profit',Value:current.tp||'—'}]}/></Card></div></Card>
        <div className="grid grid-4" style={{marginTop:16}}><Card><SectionTitle title="Strategy Used"/><strong>{current.strategy||'—'}</strong></Card><Card><SectionTitle title="Market Regime"/><strong>{current.marketRegime||'—'}</strong></Card><Card><SectionTitle title="Confidence Score"/><ConfidenceRing value={Number(current.confidence||0)} size={88}/></Card><Card><SectionTitle title="Tags"/><div className="pill-row">{(current.tags||['bot-only','mt5']).map((t:string)=><Tag color="purple" key={t}>{t}</Tag>)}</div></Card></div>
        <div className="grid grid-3" style={{marginTop:16}}><Card><SectionTitle title="Trade Context"/><Checklist items={[{label:'Session',value:current.session||'—'},{label:'Higher Timeframe Trend',value:current.htfTrend||'—'},{label:'News Impact',value:current.newsImpact||'—'},{label:'Structure',value:current.structure||'—'}]}/></Card><Card><SectionTitle title="Lessons Learned"/><p className="muted">{current.lessons||'No lesson recorded yet.'}</p><SectionTitle title="What I’ll Do Differently"/><p className="muted">{current.improvement||'Review after more bot-only samples.'}</p></Card><Card><SectionTitle title="AI Notes"/><p className="muted">{current.aiNotes||'AI notes will populate after live bot trades are reviewed.'}</p><Tag color="purple">AI Score: {current.aiScore||'—'}</Tag></Card></div>
      </div>
    </div>
  </div>
}
