import { useEffect, useState } from 'react';
import { BarChart3, BrainCircuit, Grid2X2, Settings2, Table2 } from 'lucide-react';
import { Card, DataTable, PageHeader, ProgressBar, SectionTitle, Tag, ToggleSwitch } from '../components/ui';
import { api } from '../lib/api';
const pick=(v:any,d:any='—')=>v===undefined||v===null||v===''?d:v;
export default function Strategies(){
 const [items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[editing,setEditing]=useState<any|null>(null),[view,setView]=useState<'cards'|'table'>('cards'),[msg,setMsg]=useState('');
 const load=async()=>{const d=await api.strategies(); const arr=Array.isArray(d)?d:[]; setItems(arr); setSelected((s:any)=>s||arr[0]||null)}; useEffect(()=>{load()},[]);
 const toggle=async(s:any,on:boolean)=>{on?await api.enableStrategy(s.id):await api.disableStrategy(s.id); await load()};
 const saveConfig=async()=>{if(!editing)return; await api.configureStrategy(editing); setMsg('Strategy configuration saved.'); setEditing(null); await load(); setTimeout(()=>setMsg(''),2500)};
 const rows=items.map((s:any)=>({Strategy:s.name,WinRate:s.winRate??s.win_rate??0,Expectancy:s.expectancyR??s.expectancy??'—',MaxDD:s.maxDrawdown??s.maxDD??'—',Trend:s.regime||'—',London:s.sessions?.includes?.('London')?'●':'—',NY:s.sessions?.includes?.('New York')?'●':'—',News:s.name?.includes?.('News')?'●':'—'}));
 return <div className="responsive-two">
  <div>
   <PageHeader title="Strategies" subtitle="Adaptive strategy arsenal designed for XAUUSD across all market conditions." right={<><Tag color="purple">AI-Powered</Tag><span className="tiny muted">Auto-Select Mode</span><ToggleSwitch checked={true}/><button className="outline-button" onClick={()=>setView(view==='cards'?'table':'cards')}>{view==='cards'?<Table2 size={14}/>:<Grid2X2 size={14}/>} {view==='cards'?'Table':'Cards'}</button></>}/>
   {msg&&<Card style={{marginBottom:16}}><span className="positive">{msg}</span></Card>}
   {view==='cards'?<div className="grid grid-4">{items.map((s:any,i:number)=><Card key={s.id||i} className={`strategy-card ${selected?.id===s.id?'selected':''}`} onClick={()=>setSelected(s)}><SectionTitle title={s.name||s.id} right={<Tag color={s.enabled!==false?'green':'red'}>{s.enabled!==false?'Active':'Off'}</Tag>}/><p className="muted">{s.description||'Institutional XAUUSD setup engine.'}</p><div className="grid grid-3"><div><div className="label">Win Rate</div><strong>{pick(s.winRate??s.win_rate,0)}%</strong></div><div><div className="label">Expectancy</div><strong className="positive">{pick(s.expectancyR??s.expectancy,'—')}</strong></div><div><div className="label">Max DD</div><strong>{pick(s.maxDrawdown??s.maxDD,'—')}</strong></div></div><div className="pill-row"><Tag color="blue">{s.primaryTimeframe||s.timeframe||'M15'}</Tag><Tag color="gold">{s.regime||'Adaptive'}</Tag></div><div className="detail-row"><span>Enabled</span><ToggleSwitch checked={s.enabled!==false} onChange={(v)=>toggle(s,v)}/></div></Card>)}</div>:<Card><DataTable columns={['Strategy','WinRate','Expectancy','MaxDD','Trend','London','NY','News']} rows={rows}/></Card>}
   <div className="grid grid-2" style={{marginTop:16}}><Card><SectionTitle icon={<BrainCircuit size={18}/>} title="Adaptive Strategy Engine"/><div className="grid grid-2"><Card soft><strong>Market Regime</strong><p className="muted">Trend / Range / Volatile</p></Card><Card soft><strong>Volatility</strong><p className="muted">ATR / HV clusters</p></Card><Card soft><strong>Momentum</strong><p className="muted">RSI / MACD / ADX</p></Card><Card soft><strong>Liquidity</strong><p className="muted">Sweeps / OB / FVG</p></Card><Card soft><strong>Session Context</strong><p className="muted">London / NY / Overlap</p></Card><Card soft><strong>News & Events</strong><p className="muted">Impact & timing rate</p></Card></div><div style={{marginTop:12}}><div className="detail-row"><span>Model Confidence</span><strong className="positive">87%</strong></div><ProgressBar value={87}/></div></Card><Card><SectionTitle icon={<BarChart3 size={18}/>} title="Strategy Comparison Matrix"/><DataTable columns={['Strategy','WinRate','Expectancy','MaxDD','Trend','London','NY','News']} rows={rows}/></Card></div>
   <Card style={{marginTop:16}}><SectionTitle title="Backtest Performance"/><DataTable columns={['Strategy','Total Trades','Win Rate','Expectancy R','Profit Factor','Total R','Max DD','Sharpe','Calmar','Sample']} rows={items.map((s:any,i)=>({'Strategy':s.name,'Total Trades':s.totalTrades??0,'Win Rate':`${s.winRate??0}%`,'Expectancy R':s.expectancyR??'—','Profit Factor':s.profitFactor??'—','Total R':s.totalR??'—','Max DD':s.maxDrawdown??'—','Sharpe':s.sharpe??'—','Calmar':s.calmar??'—','Sample':s.samplePeriod??'Live only'}))}/></Card>
  </div>
  <div className="right-stack side-panel-sticky"><Card><SectionTitle title="Selected Strategy" right={<Tag color={selected?.enabled!==false?'green':'red'}>{selected?.enabled!==false?'Active':'Off'}</Tag>}/><h3>{selected?.name||'Select strategy'}</h3><p className="muted">{selected?.description||'Choose a strategy card to inspect.'}</p><div className="detail-row"><span>Primary Timeframes</span><strong>{selected?.primaryTimeframe||'M15, H1'}</strong></div><div className="detail-row"><span>Best Sessions</span><strong>{Array.isArray(selected?.sessions)?selected.sessions.join(', '):'London, New York'}</strong></div><div className="detail-row"><span>Min Confidence</span><strong>{selected?.minConfidence||70}%</strong></div><div className="detail-row"><span>Risk per Trade</span><strong>{selected?.riskPerTrade||1}%</strong></div><div className="detail-row"><span>Win Rate</span><strong className="positive">{selected?.winRate||0}%</strong></div><button className="gold-button" style={{width:'100%',marginTop:14}} onClick={()=>setEditing(selected)}><Settings2 size={14}/> Configure Strategy</button></Card><Card><SectionTitle title="Why AI Chose This Strategy" right={<Tag color="green">Live</Tag>}/><div className="checklist"><div className="checklist-item"><span>Market Regime</span><strong>Evaluated</strong></div><div className="checklist-item"><span>Momentum Alignment</span><strong>Checked</strong></div><div className="checklist-item"><span>Volatility Expansion</span><strong>Checked</strong></div><div className="checklist-item"><span>Session Advantage</span><strong>Checked</strong></div></div><div style={{marginTop:12}}><ProgressBar value={87}/></div></Card>{editing&&<Card><SectionTitle title="Configure Strategy" right={<button className="ghost-button" onClick={()=>setEditing(null)}>Close</button>}/><label className="form-row"><span>Name</span><input className="input" value={editing.name||''} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label className="form-row"><span>Min Confidence</span><input className="input" type="number" value={editing.minConfidence||70} onChange={e=>setEditing({...editing,minConfidence:Number(e.target.value)})}/></label><label className="form-row"><span>Risk %</span><input className="input" type="number" step="0.1" value={editing.riskPerTrade||1} onChange={e=>setEditing({...editing,riskPerTrade:Number(e.target.value)})}/></label><button className="gold-button" style={{width:'100%'}} onClick={saveConfig}>Save Configuration</button></Card>}</div>
 </div>
}
