import { useEffect, useMemo, useState } from 'react';
import { Bot, Download, PlayCircle, RefreshCcw, SlidersHorizontal, X } from 'lucide-react';
import { Card, DataTable, MetricCard, PageHeader, ProgressBar, SectionTitle, SideBadge, Tag } from '../components/ui';
import { api, downloadExport } from '../lib/api';
const notify=(title:string,body:string,sound='success')=>window.dispatchEvent(new CustomEvent('godmode:notify',{detail:{title,body,sound}}));
const money=(v:any,c='')=>`${Number(v||0)>=0?'+':''}${c?c+' ':''}${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const toDate=(value:any)=>{ if(!value) return ''; const d=new Date(value); return Number.isNaN(d.getTime()) ? String(value).slice(0,10) : d.toISOString().slice(0,10); };
const price=(v:any)=>Number(v||0)>0?Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:3}):'—';
function TradeLine({label,value,tone}:{label:string;value:any;tone?:'green'|'red'|'gold'}){return <div className="trade-line"><span>{label}</span><strong className={tone==='green'?'positive':tone==='red'?'negative':tone==='gold'?'gold':''}>{value}</strong></div>}
function Step({title,body,active=false}:{title:string;body:string;active?:boolean}){return <div className={`timeline-step ${active?'active':'pending'}`}><span/><div><strong>{title}</strong><p>{body}</p></div></div>}

export default function Trades(){
  const [data,setData]=useState<any>({active:[],pending:[],history:[],account:{currency:''}});
  const [tab,setTab]=useState('All Trades'),[side,setSide]=useState('ALL'),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState('');
  const [filterOpen,setFilterOpen]=useState(false),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[page,setPage]=useState(1);
  const [manual,setManual]=useState({symbol:'XAUUSD', side:'BUY', volume:0.01, sl:'', tp:''});
  const load=async()=>{setLoading(true); setData(await api.trades()); setLoading(false)};
  // Poll every 8 seconds for active trades; history is expensive (90-day MT5 query)
  useEffect(()=>{load(); const id=setInterval(load,8000); return()=>clearInterval(id)},[]);
  const currency=data?.account?.currency || data?.currency || '';
  const matchSide=(t:any)=>side==='ALL'||String(t.direction||t.side||'').toUpperCase()===side;
  const matchDate=(t:any)=>{const d=toDate(t.closeTime||t.openTime||t.date||t.time); if(dateFrom && d<dateFrom) return false; if(dateTo && d>dateTo) return false; return true;};
  const active=useMemo(()=>((data.active||[]).filter(matchSide)),[data,side]);
  const pending=useMemo(()=>((data.pending||[]).filter(matchSide)),[data,side]);
  const history=useMemo(()=>((data.history||[]).filter((t:any)=>matchSide(t)&&matchDate(t))),[data,side,dateFrom,dateTo]);
  const show=(m:string,ok=true)=>{setMessage(m); notify(ok?'Trade action':'Trade blocked',m,ok?'success':'warning'); setTimeout(()=>setMessage(''),4200)};
  const selected=active[0]||history[0]||{};
  const hasActive=active.length>0 && Boolean(active[0]?.ticket);
  const manage=(payload:any)=>api.manageLiveTrade(payload).then((r:any)=>show(`Management action: ${r?.action||r?.message||'checked'}`, true));
  const clearFilters=()=>{setSide('ALL');setDateFrom('');setDateTo('');setPage(1)};
  const manualTrigger=()=>api.manualTradeTrigger({ ...manual, sl: manual.sl || undefined, tp: manual.tp || undefined, comment:'GODMODE_manual_ticket' }).then((r:any)=>{show(r?.message || (r?.ok?'Manual trade request sent':'Manual trade failed'), Boolean(r?.ok)); load();});
  const autoTick=()=>api.autoTradingTick().then((r:any)=>{const decision=r?.actionMatrix?.decision; const blocks=r?.actionMatrix?.blockedReasons || decision?.decisionBlocks || []; const detail=blocks?.length ? ` ${blocks.slice(0,2).join('; ')}` : ''; show(r?.message ? `${r.message}${detail}` : (r?.ok?'Auto trade fired':'Auto trade checked'), Boolean(r?.ok)); load();});
  const netToday=Number(data.netPnlToday||0), openPnl=active.reduce((a:number,t:any)=>a+Number(t.pnlUsd||0),0);
  const pageRows=history.slice((page-1)*8,page*8); const pages=Math.max(1,Math.ceil(history.length/8));
  // Compute pagination range so current page is always visible (not clamped to 1-5)
  const pageStart=Math.max(1,Math.min(page-2,pages-4)); const pageEnd=Math.min(pages,pageStart+4);
  const showActive=tab==='All Trades'||tab==='Active'; const showPending=tab==='All Trades'||tab==='Pending'; const showClosed=tab==='All Trades'||tab==='Closed'; const showCanceled=tab==='Canceled';
  const tpProgress=Number(selected.tpProgress||0);
  return <div className="layout-right trades-layout exact-trades">
    <div>
      <PageHeader title="Trades" subtitle="Monitor, manage and analyze GodMode bot trades in real time." right={<><button className="outline-button" onClick={()=>setFilterOpen(!filterOpen)}><SlidersHorizontal size={14}/> Filter</button><button className="outline-button" onClick={load}><RefreshCcw size={14}/> {loading?'Refreshing':'Refresh'}</button><button className="outline-button" onClick={()=>downloadExport('trades','csv')}><Download size={14}/> Export CSV</button></>}/>
      {message&&<Card className="action-banner"><span>{message}</span></Card>}
      <div className="trade-tabs">{['All Trades','Active','Pending','Closed','Canceled'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>{setTab(x);setPage(1)}}>{x}</button>)}</div>
      <div className="top-kpis trade-kpis"><MetricCard label="Net PnL Today" value={money(netToday,currency)}/><MetricCard label="Open PnL" value={money(openPnl,currency)}/><MetricCard label="Win Rate" value={`${Number(data.winRate||0).toFixed(1)}%`}/><MetricCard label="Profit Factor" value={Number(data.profitFactor||0).toFixed(2)}/><MetricCard label="Expectancy" value={money(data.expectancy||0,currency)}/></div>
      {filterOpen&&<Card className="filter-card"><SectionTitle title="Trade filters" right={<button className="ghost-button" onClick={()=>setFilterOpen(false)}><X size={13}/> Close</button>}/><div className="filter-row premium-filter"><label><span>Direction</span><select className="input" value={side} onChange={e=>setSide(e.target.value)}><option>ALL</option><option>BUY</option><option>SELL</option></select></label><label><span>Date from</span><input className="input" type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label><span>Date to</span><input className="input" type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><button className="ghost-button" onClick={clearFilters}>Clear Filter</button></div></Card>}
      {showActive&&<Card className="trade-table-card"><SectionTitle title={`Active Trades (${active.length})`}/><DataTable columns={['Symbol','Direction','Lots','Entry Price','Current Price','PnL USD','PnL %','TP Progress','Open Time','Action']} rows={active} renderCell={(r,c)=>{if(c==='Direction')return <SideBadge side={r.direction}/>;if(c==='Symbol')return <><strong>{r.symbol}</strong><div className="tiny muted">{r.name||'Gold / U.S. Dollar'}</div></>;if(c==='PnL USD')return <span className={Number(r.pnlUsd)>=0?'positive':'negative'}>{money(r.pnlUsd,currency)}</span>;if(c==='TP Progress')return <div style={{minWidth:120}}><span className="tiny">{r.tpLabel || 'LIVE'} {r.tpProgress || 0}%</span><ProgressBar value={Number(r.tpProgress||0)}/></div>;if(c==='Action')return <button className="gold-mini" onClick={()=>manage({...r,profitR:1.2})}>Manage</button>;const m:any={'Entry Price':'entryPrice','Current Price':'currentPrice','Open Time':'openTime','PnL %':'pnlPct'};return r[m[c]||c.toLowerCase()]??'—'}}/></Card>}
      {showPending&&<Card className="trade-table-card"><SectionTitle title={`Pending Orders (${pending.length})`}/><DataTable columns={['Symbol','Type','Direction','Lots','Price','Trigger','Expiry','Status','Action']} rows={pending} renderCell={(r,c)=>c==='Direction'?<SideBadge side={r.direction}/>:c==='Status'?<Tag color="green">{r.status}</Tag>:c==='Action'?<div className="button-wrap"><button className="ghost-button" onClick={()=>api.modifyTrade({ticket:r.ticket}).then((res:any)=>show(res?.message||'Modify request sent',Boolean(res?.ok)))}>Modify</button><button className="ghost-button" onClick={()=>api.closeTrade({ticket:r.ticket}).then((res:any)=>{show(res?.message||'Cancel request sent',Boolean(res?.ok));load()})}>Cancel</button></div>:r[c.toLowerCase()] ?? r[c] ?? '—'}/></Card>}
      {showClosed&&<Card className="trade-table-card"><SectionTitle title="Closed Trades History" right={<span className="tiny muted">Showing {pageRows.length} of {history.length}</span>}/><DataTable columns={['Symbol','Direction','Lots','Entry Price','Exit Price','PnL USD','PnL %','Hold Time','Close Time','Reason']} rows={pageRows} renderCell={(r,c)=>{if(c==='Direction')return <SideBadge side={r.direction||r.side}/>;if(c==='PnL USD')return <span className={Number(r.pnlUsd)>=0?'positive':'negative'}>{money(r.pnlUsd,currency)}</span>;const m:any={'Entry Price':'entryPrice','Exit Price':'exitPrice','Close Time':'closeTime','PnL %':'pnlPct','Hold Time':'holdTime'};return r[m[c]||c.toLowerCase()] ?? r[c] ?? '—'}}/><div className="pagination"><button className="ghost-button" disabled={page<=1} onClick={()=>setPage(page-1)}>‹</button>{pageStart>1&&<span className="muted">…</span>}{Array.from({length:pageEnd-pageStart+1},(_,i)=>pageStart+i).map(n=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}>{n}</button>)}{pageEnd<pages&&<span className="muted">…</span>}<button className="ghost-button" disabled={page>=pages} onClick={()=>setPage(page+1)}>›</button></div></Card>}
      {showCanceled&&<Card className="trade-table-card"><SectionTitle title="Canceled Orders"/><p className="muted">Canceled bot orders will appear here immediately after a GodMode pending-order cancellation is confirmed.</p></Card>}
    </div>
    <div className="right-stack trade-inspector side-panel-sticky">
      <Card><SectionTitle title={`${selected.symbol||'XAUUSD'} ${selected.direction||selected.side||'—'}`} right={<Tag color={hasActive?'green':'gold'}>{hasActive?'Active':'No active trade'}</Tag>}/><p className="muted">{hasActive ? (selected.name||'Gold / U.S. Dollar') : 'The live management panel activates only when a GodMode bot trade is open.'}</p><h1 className={Number(selected.pnlUsd)>=0?'positive':'negative'}>{hasActive?price(selected.currentPrice||selected.exitPrice):'—'}</h1><div className="detail-row"><span>Ticket</span><strong>{hasActive?selected.ticket:'—'}</strong></div><div className="detail-row"><span>Magic Number</span><strong>{hasActive?(selected.magicNumber||selected.magic):'—'}</strong></div><div className="detail-row"><span>Comment</span><strong>{hasActive?selected.comment:'—'}</strong></div><div className="detail-row"><span>Lots</span><strong>{hasActive?(selected.lots||selected.volume):'—'}</strong></div><div className="detail-row"><span>Open Time</span><strong>{hasActive?selected.openTime:'—'}</strong></div><div className="detail-row"><span>Strategy</span><strong>{hasActive?(selected.strategy||'GodMode Bot'):'Waiting'}</strong></div>{hasActive&&<div style={{marginTop:12}}><span className="tiny muted">TP Progress</span><ProgressBar value={tpProgress}/></div>}</Card>
      {hasActive&&<><Card><SectionTitle title="Risk & Execution"/><TradeLine label="Stop Loss" value={price(selected.sl)} tone="red"/><TradeLine label="Take Profit 1" value={price(selected.tp1||selected.tp)} tone="green"/><TradeLine label="Take Profit 2" value={price(selected.tp2)} tone="green"/><TradeLine label="Take Profit 3" value={price(selected.tp3)} tone="green"/><TradeLine label="Break-even" value={selected.beMoved?'Active':'Armed'} tone="green"/><TradeLine label="Trailing Stop" value={selected.trailingStop?'Active':'Ready'} tone="green"/><TradeLine label="Risk" value={selected.risk||'AI controlled'}/><TradeLine label="Risk / Reward" value={selected.rr||'Dynamic'}/><TradeLine label="Execution Quality" value={selected.executionQuality||'Measured'}/><TradeLine label="Slippage" value={selected.slippage??'—'}/></Card>
      <Card><SectionTitle title="Trade Timeline"/><div className="timeline sleek-timeline"><Step title="Open" active body={`Trade opened at ${price(selected.entryPrice)}`}/>{tpProgress>=33&&<Step title="TP1" active body="TP1 reached. Risk reduced."/>}{selected.beMoved&&<Step title="Break-even" active body="Stop moved to BE + costs."/>}{selected.trailingStop&&<Step title="Trailing" active body="Structure trailing activated."/>}{tpProgress>=66&&<Step title="TP2" active body="Runner protected."/>}{tpProgress>=100&&<Step title="Final TP" active body="Target sequence completed."/>}</div><textarea className="input note-input" placeholder="Add note..."/></Card></>}
      <Card><SectionTitle title="Manual Trade Trigger" right={<Tag color="red">Live gated</Tag>}/><div className="manual-ticket"><label className="form-row"><span>Symbol</span><input className="input" value={manual.symbol} onChange={e=>setManual({...manual,symbol:e.target.value.toUpperCase()})}/></label><label className="form-row"><span>Side</span><select className="input" value={manual.side} onChange={e=>setManual({...manual,side:e.target.value})}><option>BUY</option><option>SELL</option></select></label><label className="form-row"><span>Lots</span><input className="input" type="number" step="0.01" value={manual.volume} onChange={e=>setManual({...manual,volume:Number(e.target.value)})}/></label><label className="form-row"><span>SL</span><input className="input" value={manual.sl} onChange={e=>setManual({...manual,sl:e.target.value})} placeholder="optional"/></label><label className="form-row"><span>TP</span><input className="input" value={manual.tp} onChange={e=>setManual({...manual,tp:e.target.value})} placeholder="optional"/></label><button className="gold-button full" onClick={manualTrigger}><PlayCircle size={14}/> Open Manual Trade</button></div></Card>
      <Card><SectionTitle title="Live Management Controls" right={<Tag color="purple">AI gated</Tag>}/><div className="grid"><button className="outline-button" disabled={!hasActive} onClick={()=>manage({...selected, profitR:1.2})}>Manage Trade</button><button className="outline-button" disabled={!hasActive} onClick={()=>api.modifyTrade({ticket:selected.ticket, sl:selected.entryPrice}).then((r:any)=>show(r?.message||'Break-even modify sent',Boolean(r?.ok)))}>Move to Break-even</button><button className="outline-button" disabled={!hasActive} onClick={()=>api.modifyTrailingStop({ticket:selected.ticket, structure:'M5'}).then((r:any)=>show(r?.message||'Trailing stop request sent',Boolean(r?.ok)))}>Trail Structure</button><button className="outline-button" disabled={!hasActive} onClick={()=>api.executePyramiding({position:selected}).then((r:any)=>show(r?.message||'Pyramid checked',Boolean(r?.ok)))}>Pyramid Only If Proven</button><button className="ghost-button" disabled={!hasActive} onClick={()=>api.closeTrade({ticket:selected.ticket, symbol:selected.symbol, direction:selected.direction, lots:selected.lots, entryPrice:selected.entryPrice, currentPrice:selected.currentPrice, pnlUsd:selected.pnlUsd}).then((r:any)=>{show(r?.message||'Close request sent',Boolean(r?.ok));load()})}>Close Trade</button><button className="gold-button full" onClick={autoTick}><Bot size={14}/> Run Auto Trade Check Now</button></div></Card>
    </div>
  </div>;
}
